### ISSUE TITLE
Should we use read.csv or read_csv in all of our lessons?

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Spatial-Vector#1]
we should be consistent across lessons @tracykteal @jduckles -- any preferences from SWC or DC teaching experiences?

**Comment by jduckles** [comment]
I could go either way on this. `read_csv` introduces a dependency on `readr` and is more in line with the hadleyverse.  `read.csv` is batteries included, which I tend to lean toward, but I understand the need for updating the defaults. I think they both come with a bit of cognitive load.  Sorry I can't be more helpful.

**Comment by lwasser** [comment]
thank you @jduckles . i guess we can sit on this for a bit of time and revisit! i'll leave this issue open for the time being.

**Comment by lwasser** [comment]
I am closing this as we have decided to go base R for the time being !
