### ISSUE TITLE
Generalized file paths

### ISSUE THREAD

**Issue by jsta** [data-lessons/NEON-R-Spatial-Vector#10]
Would be much easier for people to test this repo if they were able to knit the files themselves. I'm thinking specifically about the `setwd()` statements.

**Comment by jsta** [comment]
One solution might be to change the `setwd()` statement to point to a _data_ folder within the repo. However, we would never actually commit the data files.

**Comment by lwasser** [comment]
hey @jsta trying to follow. All of the files are knit at once using the knitr script that i wrote. Are you saying that in the RMD files, there are setwd() calls that look for say my folder structure rather than someone elses? I think in the long run, we envision people using the actual built pages  like this one

http://data-lessons.github.io/NEON-R-Spatial-Vector//R/open-shapefiles-in-R/

also we can add a link to the R file which is also rendered via the knitr script (purled). So people could use that locally but would still have to update working directories.

we just use the RMD files to build the final web output. But again - very open to ideas if i better understand what you are thinking.

**Comment by jsta** [comment]
For example, have a look at the beginning of the second code chunk here: [http://data-lessons.github.io/NEON-R-Spatial-Vector//R/csv-to-shapefile-R/](http://data-lessons.github.io/NEON-R-Spatial-Vector//R/csv-to-shapefile-R/).

What if we changed:
`setwd("~/Documents/data/1_DataPortal_Workshop/1_WorkshopData")`

to:
`setwd("_data")`

For the purposes of developing the lesson, we would then assume that people have the data in a subfolder **within** the repo. You, the other lesson developers, and myself could have the data in this subfolder but not commited to the repo. This way we do not need to have your specific path to the data set up on our machines in order to run the code chunks.

**Comment by mjones01** [comment]
From @lwasser in the Pull request: (added here so we don't have to go back and forth)
ok - referring to issue #10 -- let's address the working directory issue via that issue and make a call. i'm inclined to remove the setwd code throughout but maybe have something commented that says - be sure to set your working directory. leave as is and address via the issue. :)

**Comment by mjones01** [comment]
Since many of the codes for pulling in other files assumes that the last bit of the working directory is 1_WorkshopData/  (or whatever they call the file) we need to at least give directions to have them set that as the last folder in the path to the working directory, therefore other code will work.

**Comment by lwasser** [comment]
Yes! I agree. And we will have this issue for EVERY lesson we post. SO... what about this
1. in each lesson we have a commented out - setup working directory chunk. It has code that is like this

Before you go any further, please be sure you have set your working directory to the location where your data are stored on your computer. 

``````
```{r working-dir }
#be sure to set your working directory if you don't have a R Studio project open
#setwd("yourWorkingDirectoryHere")
```
``````

We could then potentially create a lesson on setting up working directories and R proj files as well. Each lesson could have the SAME content.

I agree with @jsta - we DEFINITELY don't want the code to set the wd in the lessons. that will get confusing quickly. We could tell people to place data in a data folder somewhere.

**Comment by mjones01** [comment]
@jsta  and @lwasser 
Possible working directory solution across  #WorkWithData lessons.
In the Outcomes box at the top of each lesson after the Data to Download Section insert this Set Working Directory section.
####Setting the Working Directory
The code in this lesson assumes that you have set your working directory to the
location of the unzipped file of data downloaded above.  If you would like a 
refresher on setting the working directory, please view the <a href="XXX" target="_blank">Setting A Working Directory In R</a> lesson prior to beginning the lesson.  
</div>
It links to a, yet to be created, simple page explaining downloading & unzipping the data and then setting a working directory to it.  Including both PC and Mac pathways (and linux, etc if different?  I always assume if someone is using Linux they know their way around the basics).  

In the initial code chuck for EACH lesson when one should set the working directory we include:
#set working directory to ensure R can find the file we wish to import
#setwd("workingDirHere")

**Comment by mjones01** [comment]
I'd love response comments soonish as I think I'll start implementing this in the Time Series lesson set I'm working on.

**Comment by lwasser** [comment]
Note - i created the beginning of such a tutorial here (in the grey box). We could generalize the zip file names potentially and build a page.

http://neondataskills.org/Data-Workshops/ESA15-Big-Data-In-R/

I like having the code below in each lesson

```
#set working directory to ensure R can find the file we wish to import
#setwd("working-dir-path-here")

```

**Comment by lwasser** [comment]
Also - i think the content editing / refining is a priority over creating a new page for this week. The content needs a lot of editing and refinement from what i can see still. one thing at a time! :) it will all come together!

**Comment by mjones01** [comment]
Excellent.   I can work on that AFTER the current lessons are closer to a finished product.   (Oh you just said that)

**Comment by lwasser** [comment]
yup :) we are on the same page! thank you for being on top of things @mjones01

**Comment by mjones01** [comment]
Close? 
- lessons have a generalized setwd path & link to learning more about how to do it.  
- all paths are (will soon be?) updated to new folder names (same as FigShare folders)

**Comment by lwasser** [comment]
I think with our knitr build and local rendering this is covered. Perhaps we can document the local build in our template repo --( FUTURE task).
