### ISSUE TITLE
Vector 04: Show example of setting crs without borrowing from an existing file. 

### ISSUE THREAD

**Issue by mjones01** [data-lessons/NEON-R-Spatial-Vector#101]
@lwasser I saw your recent response (10 April) to comment on Vector 04 (first part only).  I think Michael was attempting to ask for an example of how to set the CRS using a proj4 string (or EPSG #), as the same question come up when teaching this today.  
We currently only show how to borrow an CRS but I can see a Data Tip showing both using proj4 and EPSG # structure when assigning CRS to reproject. .

**Comment by jsta** [comment]
:+1:  I agree with this

**Comment by lwasser** [comment]
This issue was moved to datacarpentry/R-spatial-raster-vector-lesson#95
