### ISSUE TITLE
Vector 02: Challenge Histosols & Intceptisol switched 

### ISSUE THREAD

**Issue by mjones01** [data-lessons/NEON-R-Spatial-Vector#102]
In workshop several participants used different code and got the reverse. I checked and the furthest south point should be an Inceptisol not a Histosol.  
Cause?  levels() alphabetizes but we use unique() not levels().  Therefore when we manually assign the name in the legend, assuming these are alphabetized, they are represented backwards.

**Comment by mjones01** [comment]
Fix: 
instead of manually typing what we want in the legend, automate it.  
~ line 200:
legend=c(levels(plotLocations$soilTypeOr),levels(roads_HARV$TYPE)),

**Comment by lwasser** [comment]
This issue was moved to datacarpentry/R-spatial-raster-vector-lesson#94
