### ISSUE TITLE
2016-07-21 Workshop Takeaways

### ISSUE THREAD

**Issue by jsta** [data-lessons/NEON-R-Spatial-Vector#103]
I ran a workshop using these materials. Our group ran into the following pain points:
- Plot appearance can be much different depending on the size of the **RStudio** _plot pane_
- Learners can be tripped up if they mistakenly use `SpatialMultiPointsDataFrame()` rather than `SpatialPointsDataFrame` 
- The materials could be improved by adding a link to possible `pch` values
- The challenge at the end of lesson 00 requires knowledge of loading rasters which has not yet been introduced

**Comment by lwasser** [comment]
Hey @jsta - why don't you turn the above into a list so we can knock them out? just use the following syntax for each bullet

```
- [ ] list item
```

- [ ] list item looks like this.

We taught raster first SO the challenge at the end of L00 wasn't a problem. it sounds like you taught vector first. To avoid this - i think we should merge both repos and have all activities that combine raster and vector be included in the last batch of lessons. this will avoid all of these issues. 

The plot pane is a huge pain and there's no great way to deal with it. i agree!

**Comment by lwasser** [comment]
This issue was moved to datacarpentry/R-spatial-raster-vector-lesson#93
