### ISSUE TITLE
Add Tif data file to Lesson 02 and 03

### ISSUE THREAD

**Issue by snewman29** [data-lessons/NEON-R-Spatial-Vector#11]
Please add the NEON_remotesensing zip file to the Lesson 02 and 03 data download sections :).

**Comment by mjones01** [comment]
Actually I'm going to expand this issue to review all Data to Download sections.  As the titles from what to download doesn't match the file names.   (e.g. raster & in situ collected vegetation data = BoundaryFiles.zip?) .

**Comment by lwasser** [comment]
Agreed. What we should do is come up with a block of text for EACH download in the figshare repo. Then use that for each page as necessary. it's definitely wrong on many pages! thank you for catching this. i haven't heard back from eve on the figshare account.

**Comment by mjones01** [comment]
Close.  This is done.
