### ISSUE TITLE
Lesson 00: Intro Suggestions

### ISSUE THREAD

**Issue by snewman29** [data-lessons/NEON-R-Spatial-Vector#13]
I really like the navigation menu on the right of the lesson to help you jump around the activity. It was also helpful to have some review content like “About Vector Data” to remind the learner what vector data is if they need a quick refresher.

The Recommended Reading section was a little confusing for this lesson. Based on where it is placed in the lesson and how it is described, I was at first assuming that I should read these materials before I dig into the rest of Lesson 00. But, when I clicked on the links I realized that the material was actually for additional learning after Lesson 00. It might be worth revisiting this section so learners realize that this is Additional learning material for after the lesson.

**Comment by mjones01** [comment]
I was thinking about this as well.  Would it be worth having a Things to Know/Do before lesson section and a Further Reading section?

**Comment by mjones01** [comment]
My suggestions applies across all lessons/ modules, not just 00.

**Comment by lwasser** [comment]
Yes -- i think we should think about this. 

I think we should think about the following
1. the lesson set - links to all related lessons in the set. this should go up top
2. recommended reading - PRE doing the lesson
3. further reading

What if we come up with a template and then apply that template to ALL LESSONS. and ofcourse i'm open to what this looks like but something like

# Lesson Set (or whatever langauge we want to use)]
- link to l01
- link to l02
- etc..

# Recomended Reading Before Your Start
- link
- link

# Further Reading
- link

**Comment by mjones01** [comment]
Close?  This section has changed to address issue.

**Comment by lwasser** [comment]
yes. I think using "Additional resources" is general enough. We can always add "Required reading" as a pre-lesson requirement if need be.
