### ISSUE TITLE
Lesson 00: Shapefiles: Points, Lines, and Polygons section

### ISSUE THREAD

**Issue by snewman29** [data-lessons/NEON-R-Spatial-Vector#15]
Typo: Each vector in the shapefile often has a set *os associated attributes that describe the data.

**Comment by jsta** [comment]
Thanks for looking into this. However, I see no typo in the underlying Rmd file. The line currently reads:

_Each vector in the shapefile often has a set of associated `attributes` that describe the data._

Must be a website rendering issue. @lwasser

**Comment by mjones01** [comment]
This is an issue of my reviewing of the Rmd code but us not yet re-kniting/postiing the code.  So yes, the posted pages are a bit behind the code. This usually won't be a problem except in these early stages when one or more people are doing lots of edits.

**Comment by mjones01** [comment]
Issue can be closed.

**Comment by lwasser** [comment]
Ok closing the issue as it seems the typo was fixed! @mjones01 should i reknit this today? or should i wait for more edits?
