### ISSUE TITLE
Lesson 00: On Your Own Activity section

### ISSUE THREAD

**Issue by snewman29** [data-lessons/NEON-R-Spatial-Vector#17]
In the On Your Own Activity, the black box that contains code has the error below: 
## Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv, : Cannot open layer

The HARV_roadStream file doesn’t exist. I think this is supposed to be HARV_roads instead.

**Comment by mjones01** [comment]
Fixed.  Close issue.

**Comment by lwasser** [comment]
closing. thanks!
