### ISSUE TITLE
Lesson 00: 404 Error

### ISSUE THREAD

**Issue by snewman29** [data-lessons/NEON-R-Spatial-Vector#18]
404 Error comes up for link to:
More on Packages in R - Adapted from Software Carpentry.

**Comment by lwasser** [comment]
oops - the URL should be 

```
<a href="http://neondataskills.org/R/Packages-In-R/" target="_blank">More on Packages in R - Adapted from Software Carpentry.</a>
```

@mjones01 i just don't' want to cause conflicts knowing you're actively fixing things...or else i'd change these myself.

**Comment by mjones01** [comment]
Changed in lesson 00.  Should this be added to all the lessons under the packages needed section?

**Comment by lwasser** [comment]
@mjones01 sure - can't hurt to have it as an additional resources link?
