### ISSUE TITLE
Lesson 00: Code resizing suggestion

### ISSUE THREAD

**Issue by snewman29** [data-lessons/NEON-R-Spatial-Vector#19]
Suggestion:
The black boxes filled with the code for the lessons don’t resize with the browser window. So, for example, I brought up RStudio on one side of my screen and the Lesson on the other side so I could go back and forth more quickly between the lesson and the console. But, once I got to the coding section, this didn’t work and I had to keep flipping between screens. Not critical to the lesson, but it would be great if the code resized!

**Comment by lwasser** [comment]
interesting - what browser are you using? it resized on my mac!

**Comment by snewman29** [comment]
Oh interesting - I use Firefox on a PC :)

**Comment by lwasser** [comment]
ok perfect! i will test on firefox when i get my PC up and running! thanks @snewman29

**Comment by mjones01** [comment]
I've found that the boxes do resize (smaller, but there is a upper limit) on Chrome/Mac.  However, the boxes seems to be a bit narrower than our 80 character limit that we've set for the coding.  
@lwasser Can the box size be adjusted? It might be at 80 characters but when the code is also at 80 it chops off the last letter or adds the bottom scroll bar.

**Comment by lwasser** [comment]
@mjones01 just revisiting this issue. is the code still being chopped off? if so - can you please add an issue to our dev site about code width? then we can close this issue here. Thank you!

**Comment by lwasser** [comment]
closing this as it will be resolved with the new template whenever that is applied.
