### ISSUE TITLE
Lesson 00: Suggestions for 2nd On Your Own Activity

### ISSUE THREAD

**Issue by snewman29** [data-lessons/NEON-R-Spatial-Vector#20]
One thought: Perhaps include an additional shapefile in the data package (perhaps streams or water polygons of some kind?). Have the learner add this shapefile as well, perhaps require a certain color for the objects (ie. blue if water objects) and answer questions about the shapefile attributes.

**Comment by mjones01** [comment]
Good suggestion.  Current challenges have been re-worked to include attributes and changing colors by attributes (look for a Dec 22 or 23 re-build before checking).  Was there something else in particular you were looking for other than this?

**Comment by lwasser** [comment]
This is good! I think when i go through the lesson i'm going to think a lot about what files we used for that site! And what files we can get for other sites. :) Sarah has he hands full right now - but let's keep this open as i work through the lessons next week !
