### ISSUE TITLE
Lesson 01: Exploring Values in One Attribute secdtion

### ISSUE THREAD

**Issue by snewman29** [data-lessons/NEON-R-Spatial-Vector#24]
Typo: We can also explore individual values stored within a *particulat attribute.

**Comment by lwasser** [comment]
hey @snewman29 - thank you for the feedback. Rather than submitting 50 issues. How about ONE set of issues PER LESSON? does that work? you can go back and EDIT all of your feedback as well so there's just one issue with lots of comments on one lesson.

**Comment by snewman29** [comment]
I was wondering what would be easier - chunked out or all together. I'll fix that and just do one issue per lesson.

**Comment by lwasser** [comment]
@snewman29  - yup thank you. Just put one per lesson. And you can edit a comment so you can just place ALL FEEDBACK in one big comment per lesson. THANK YOU!

**Comment by lwasser** [comment]
@mjones01 @jsta  what do you think about my comment? and what would you prefer in your repo? separate issues or one issue with lots of stuff per lesson? i can't decide if i over reacted to the emails coming in! :)

**Comment by mjones01** [comment]
Leah,
I don't see you comment. Which issue is it under?

**Comment by mjones01** [comment]
(Thanks for the tip @lwasser on accessing this).  In my current revisions I've taken the Notes to self/ Things to fix out of the Rmd code and was going to add them as separate issues.  I do like the idea of small fixes (typos etc) being a single issue, but larger ones could probably be their own.  Does that make sense?

**Comment by mjones01** [comment]
Fixed.  Close issue.

**Comment by lwasser** [comment]
closing - fixed.
