### ISSUE TITLE
Lesson 02: What You'll Need section

### ISSUE THREAD

**Issue by snewman29** [data-lessons/NEON-R-Spatial-Vector#28]
What You’ll Need
Should R studio be written as RStudio? Might also be useful to link to both R and RStudio in this section...

I’m not entirely sure I understood this section:
“Note that there is a SpatialPoints object in R that does not allow you to store associated attributes. The SpatialPointsDataFrame allows you to store columns from your data.frame in the object.”

Does this mean that the SpatialPointsDataFrame allows you to store attributes whereas SpatialPoints object does not?

I think this sentence may need a little rewording:
The HARV_PlotLocations.csv file contains x,y locations for some plots that [where? instead of ‘that’](NEON)[http://www.neoninc.org] field crew are sampling vegetation and other ecological metrics.

**Comment by jsta** [comment]
Not sure how common it is to find or work with `SpatialPoints` objects. Maybe this level of detail is not warranted here? @lwasser

**Comment by lwasser** [comment]
@jsta yes. I agree. i made it overly complicated. let's just remove that text about spatial points and focus on spatial points DF. yea?? Go ahead and edit away!

And i agree with the rewording as well. let's make sure we capture both of these comments - they are good.

**Comment by mjones01** [comment]
RStudio fixed. 
Links- I think they should be in maybe lesson 00 of each module but seems excessive for every lesson? 
Spatial Points: reworded/ removed SpatialPoints from paragraph but retained it as a note.

**Comment by lwasser** [comment]
Ok given we have a stand alone use case... i see one alternative. We say - we recommend using R / R studio and have a link. BUT that link can be a page WE CREATE with information about both and links to both. That way, we only have to update that content in one place. Thoughts?

**Comment by mjones01** [comment]
There is still a short note warning that SpatialPoints is not the same as SpatialPointsDF.  I think this is good clarification. 

RStudio - fixed

@lwasser a bit confused by your last comment.  Has this been resolved?  Can issue be closed?

**Comment by mjones01** [comment]
PR #58
