### ISSUE TITLE
Lesson 02: Code typo

### ISSUE THREAD

**Issue by snewman29** [data-lessons/NEON-R-Spatial-Vector#29]
Code Typo: aoiBoundary <- readOGR("boundaryFiles/HARV/","HarClip_UTMZ18")
Remove the extra / after HARV

**Comment by jsta** [comment]
Not sure that this matter for functionality but it looks cleaner. Thanks.
- SHA: 91c41cb95a1bcc87f55debf0c8eb0bac4a7a8a52

**Comment by snewman29** [comment]
FYI: For me this was a functionality issue - The code worked without the extra / but did not work when it was present.

**Comment by lwasser** [comment]
I've noticed these subtle differences MAC vs PC. could also be a version thing! i think we've fixed it throughout :)

**Comment by snewman29** [comment]
Great!
