### ISSUE TITLE
Vectors aren't actually explained ???

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Spatial-Vector#3]
double check and make sure it's -- might need to add a bit more explanation about what a vector really is.

**Comment by mjones01** [comment]
Given that the last time I thought about vectors prior to 19 October was in 2005, I wasn't confused.  
However, I may have missed nuances if that is what you want to add.

I did have a question about the phrase: (Lesson00, line 109)"A polygon consists of 3 or more vertices that are connected and, most often, closed."  When is a polygon not closed?  All definitions I've looked up say they are closed.

**Comment by lwasser** [comment]
we can edit this. this is me thinking about it too much which isn't helpful for a beginner audience.

Polygons can be complex and have donut holes in them... eeks... so it's closed but there is a big hole in the middle which is awkward. we don't have to get into complex geometry here so let's remove the "most often" part. BUt first you need to pull down ALL changes from this repo to yours.

**Comment by mjones01** [comment]
Close?  Seems well explained (for beginner audience) at that this point.

**Comment by lwasser** [comment]
if you think it is sufficient let's close it. We can potentially flesh out the graphic colin created. he should be sending that your way soon .
