### ISSUE TITLE
Lesson 02: Code question and typo

### ISSUE THREAD

**Issue by snewman29** [data-lessons/NEON-R-Spatial-Vector#30]
I got the code below to work, but I can’t claim I followed what each piece means. I get that we’re assigning our plot.location to a spatial points data frame an that the [,1:2] references the x, y fields but I don’t really know what the rest of the code means after that.
# the x,y location values for the dataset are available in
# the x and y columns. We can use that for our spatial data point object
# we know the csv file coordinates are in the same CRS as the other shapefiles.
# we can assign this to the SpatialPointsDataFrame when we import it.

plot.locationSp <- SpatialPointsDataFrame(plot.location[,1:2],
                                                plot.location,
                                                proj4string = crs(aoiBoundary))

Remove the extra / after HARV in the following code:
roads <- readOGR("boundaryFiles/HARV/", "HARV_roads")

**Comment by mjones01** [comment]
This has been reworded in last pull request and I think it will address this issue.  Close issue.

**Comment by lwasser** [comment]
ok! addressed. closing
