### ISSUE TITLE
Lesson 02: Creating a Vector-Raster Overlay Map section

### ISSUE THREAD

**Issue by snewman29** [data-lessons/NEON-R-Spatial-Vector#33]
Possible typo: Next, we will load a raster from disk user (should this be “using”?) the raster command

-This might be a good section to hyperlink back to the Raster lesson just in case someone stumbles across this lesson but hasn’t been through the series.

What does “chm” stand for in this section of code?

**Comment by mjones01** [comment]
Type=Fixed
Link= Added to beginning in Data to Download. 
CHM= Canopy Height model.  Added to text. 
Close issue.

**Comment by lwasser** [comment]
thank you! closing.

**Comment by snewman29** [comment]
Can I add one more thing? I noticed the code in this section is showing the following Error on the page: 

## Error in plot(roads, add = TRUE): error in evaluating the argument 'x' in selecting a method for function 'plot': Error: object 'roads' not found

However - despite this error in the code, the code worked just fine for me!

**Comment by snewman29** [comment]
Also, probably because of the error above, the roads do not appear on the image below the code.

**Comment by mjones01** [comment]
@snewman29  FYI: you a now a bit ahead of where I've done my 1st review of the lesson.  Thank you for catching these errors.  I'll be fixing them in this round.

**Comment by snewman29** [comment]
Sounds great Megan! Happy to help!
