### ISSUE TITLE
Naming objects - dash, period, underscores, camelcase ? 

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Spatial-Vector#4]
Hi @tracykteal @jduckles what is the convention for naming objects in lessons. I see a combination of periods, dashes, underscores and camel case. It would be nice to have a standard for these lessons. Thank you!

**Comment by jsta** [comment]
I am a big fan of Richie Cotton's style guide @
http://4dpiecharts.com/r-code-style-guide/

**Comment by lwasser** [comment]
Wow - that's great! I love the idea of having a guide.
We should use that!

Joe - also, i made some edits to the lessons to try to get them to flow. I moved plotting with attributes to the attributes section. I also added some challenges, etc. Lesson 03 needs a bit more work - i placed some notes in the file.

But if any changes that I made bother you, please let me know!
The plotting issue is still up in the air a bit - we are having a discussion in the issues in the making pretty maps repo if you have thoughts on plot vs ggplot for final quality maps :)

## Leah

Leah A. Wasser, Ph.D.
Supervising Scientist
Education / Data Products
National Ecological Observatory Network (NEON)

## Boulder, Colorado

For free tutorials and resources on working with spatio-temporal data:
http://www.neondataskills.orghttp://www.neondataskills.org/

**Comment by jduckles** [comment]
At swcarpentry we typically use underscores like -> `this_is_my_variable`

**Comment by lwasser** [comment]
that's good to know! Thank you @jduckles !! this also is inline with the style guide that @jsta mentioned. let's go with it!
