### ISSUE TITLE
Consistency across ALL spatial lessons

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Spatial-Vector#40]
Hi All -- i think we should ensure that for EVERY spatial data lesson, we have them view the same attributes for the data. This means that we will need to have RGDAL and raster loaded regardless of whether they are working with rasters vs vectors.

Steps
1. view file attributes (tags)
Raster: 
`GDALinfo("filename.tif")
Vector:
`OGRinfo("filename.shp")
1. OPEN File
2. Explore File Attributes / metadata

```
CRS(objectName)
extent(objectName)
XRES(objectName) #rasters 
yRES(objectName) #rasters 
nlayers(objectName) #how many bands are in the raster
```
1. View units (found in the CRS string)

**Comment by mjones01** [comment]
@lwasser   I'm not sure this is 100% consistent across all lessons although it is talked about within each lesson series.   Current thoughts?  I'm happy to go back and re-work this into all the lessons.

**Comment by lwasser** [comment]
i haven't look at them again with fresh eyes. If you think it can be reworked without a huge amount of effort, let's do it! thanks! 

I think teaching good consistent workflows is good - just like is done in the time series lessons that you guys built.

**Comment by lwasser** [comment]
I think we are fairly consistent at this point. closing.
