### ISSUE TITLE
Lesson 01: Subsetting Shapefiles

### ISSUE THREAD

**Issue by mjones01** [data-lessons/NEON-R-Spatial-Vector#41]
Notes that I removed from the Rmd Files 9 Nov.:  
# I think we should plot by attribute HERE - given we are introducing attributes here
# we should also have some sort of application - maybe we want to find out in a point data set
# how many points are of type "X"
# can we run summary stats on the different categories?

Do we still want to add this? 
http://data-lessons.github.io/NEON-R-Spatial-Vector//R/shapefile-attributes-in-R/

**Comment by lwasser** [comment]
hey -- so this was a question of where content goes. I was thinking it might be better in this location. i haven't looked at these lessons in a while at a high level... but what do you think? it might be good for us to map out the lessons together on the white board and make sure we are covering everything. i can send picts to @jsta as well to get his input once we've done the map!

**Comment by mjones01** [comment]
Plotting by attribute is again in L01.  As are levels (how many of line X) and `summary`. 
Close issue?
