### ISSUE TITLE
Lesson 02: Create Metadata File

### ISSUE THREAD

**Issue by mjones01** [data-lessons/NEON-R-Spatial-Vector#44]
Removed from Rmd 9 Nov.: 
# NOTE: create metadata for this file!

 ->I believe this is in reference to HarClip_UTMZ18

Lesson 02
http://data-lessons.github.io/NEON-R-Spatial-Vector//R/csv-to-shapefile-R/

**Comment by lwasser** [comment]
@mjones01 this is great - can you please also reference the FILE that had the comment in it so we know where to go once this is done to talk about metadata?

**Comment by mjones01** [comment]
Not entirely sure what you are asking.  The Lesson that it applies to in the title of the issue.  Do you want that or the full file name that the metadata is needed for.  I wasn't exactly sure which is why I said I think it is HarClip_UTM18   >  /1_WorkshopData/boundaryFiles/HARV

**Comment by mjones01** [comment]
The lesson (as of PR https://github.com/data-lessons/NEON-R-Spatial-Vector/pull/51) is now written to look at the data itself for clues to what the data is.  
Do we still want to add a metadata file?

**Comment by lwasser** [comment]
metadata is crucial. And spatial metadata is good to familiarize oneself with. I'd like to leave this open even if i have to create EML for it.  For instance, if the CRS is missing (the prj file) you won't know what the CRS is UNLESS 
1. you have a good GIS eye and call "tell" using experience 
2. you have another layer that lines up with it perfectly.

**Comment by lwasser** [comment]
This issue was moved to datacarpentry/R-spatial-raster-vector-lesson#98
