### ISSUE TITLE
High level issues across Lessons

### ISSUE THREAD

**Issue by mjones01** [data-lessons/NEON-R-Spatial-Vector#45]
To add/ streamline all the higher level comments that apply across lessons, I've summarized here what I think the consensus about each is (or for the last one, my own idea).  

**What You'll Need**
_R & R studio_  (Issue https://github.com/data-lessons/NEON-R-Spatial-Vector/issues/28)
_Setting a working directory_ (Issue https://github.com/data-lessons/NEON-R-Spatial-Vector/issues/10)  -> This might be the place to link to a page explaining how to set working directory.  We can specify that all further code will assume that XXX file (maybe Spatio-TemporalData) will be the assumed working directory for the lesson.  

**Data to Download**  (Issue https://github.com/data-lessons/NEON-R-Spatial-Vector/issues/11)
Update each figshare link AFTER transfer to NEON figshare.  
Current solution in Lesson 00, lines 151-153. http://data-lessons.github.io/NEON-R-Spatial-Vector//R/open-shapefiles-in-R/
First, 3 lines of code chunk after loading packages
# set working directory to the directory location on your computer where
# you downloaded and unzipped the data files used in this lesson
# setwd("pathToDirHere")

**Lessons In this Set**  (Issue https://github.com/data-lessons/NEON-R-Spatial-Vector/issues/13)
New section-> list & link to all other lessons in module (& maybe other modules?in workshop)

**Recommended Readings before Lesson** (Issue https://github.com/data-lessons/NEON-R-Spatial-Vector/issues/13)
Revised section with just any pre-reading. 

**Additional Information**  (Issue https://github.com/data-lessons/NEON-R-Spatial-Vector/issues/13)
New section: Where to add other information that doesn't fit in body of lesson but we want to provide for going beyond the lesson.  Most current recommended readings will move to here.

_Workshop Page_ > do we want to create a page that discusses the workshop with overall goals, the modules/ lessons, and (in this case) explains Jessica. We then link to it in the **Recommended Readings** or **Lessons In this Set** section.   In the Temporal Series lessons we did this with lesson 00, but it isn't in Vector Data.   

File Titles-> Currently all files are 00 or whatever and then the name.  I suggest adding 2 letters before each lesson to ID the module they come from (eg. Time Series =TS, Vector Data=VD, Raster=RD).  This will help organization if they are ever all in 1 repo (which they might be at some point?  Hazy recollection of past conversation @lwasser).  

Links to other pages:  Should all open in new tab?  Currently a mixture.   If we do add    target="_blank"    to all.

**Comment by mjones01** [comment]
We need to decide how much teach lesson stands on it's own and how much it connects to previous lessons.  
Example (but idea extends beyond this one which is why I put this here and not as a single issue): 
Spatial Vector Module
Lesson 00: read in boundaryFiles/HARV/roads and named `lines`.  
Lesson 02: read in same file but this time name it `roads`.  

In Lesson 00 makes a lot of sense to call it lines as the lesson is focusing on polygons, lines, & points.  However, the layer really is roads so it makes sense to call it that later on in the lessons.  Yet, for someone going through the full module it is poor practice to load the same file and name it differently.  

Thoughts?

**Comment by lwasser** [comment]
We should be consistent. How about called it road_lines throughout?  lines is not a good descriptive object name short of calling attention to the fact it is a lines object.

**Comment by mjones01** [comment]
Close?  These issues now addressed by template repository?

**Comment by lwasser** [comment]
i'll close it. i need to review this repo one last time when i'm done with the time series stuff. but it seems we have addressed the above.
