### ISSUE TITLE
Lesson Format / Consistency - non-Rmd Code

### ISSUE THREAD

**Issue by mjones01** [data-lessons/NEON-R-Spatial-Vector#46]
**Authors/ Reviewers**
Currently: 
By: Joseph Stachelek, Leah Wasser Lesson Reviewers Megan A. Jones, Sarah Newman

I'd prefer:  
Lesson Authors: ...   (new line)
Lesson Contributors: ...  
Why? Parallel format in the author/contributor lines, contributor not reviewer as some may contribute by not review and we then don't have a add new lines,  separate lines will better accommodate different numbers of authors/ reviewers. 

**Header section & note section**
currently these abut but have different formats (slightly different grays and  header section has shadow, note doesn't).  The different format sets them apart but then they shouldn't abut.  
Another thought: Note on where data from is not part of main grey box and comes AFTER Recommended Reading.  Why not put this with the download data section?

**Notes at bottom of lesson**
_Date_ not updating even with new code.  It might being pulling from the date field (set for order) not the date modified code.  Not sure if this can be resolved and still have Lessons in correct order on Module page. 
_Authors/contributors_ no space between listed names

**Comment by lwasser** [comment]
@mjones01  Please see changes in the raster repo that address the authorship at the top of the page. 

http://data-lessons.github.io/NEON-R-Spatial-Raster/R/Introduction-to-Raster-Data-In-R/

Can we please change the title of this issue to Lesson Format / consistency or something that better describes the issue?

**Comment by mjones01** [comment]
Title changed.  Changes made to vector lesson 00 need to transfer to others.

**Comment by mjones01** [comment]
Future/ side issue: When finally publishing the lesson's should we change all the date created fields to that date?

**Comment by lwasser** [comment]
@mjones01 sure - we can change the date created and use it as a "date first published" field. i like that.

**Comment by mjones01** [comment]
These sections have been updated since this comment thread.
