### ISSUE TITLE
Lesson 03 Typos 

### ISSUE THREAD

**Issue by snewman29** [data-lessons/NEON-R-Spatial-Vector#48]
About section
Typo: from a raster that *occur[s] within

Remove extra / after HARV in code:
aoiBoundary <- readOGR("boundaryFiles/HARV/", "HarClip_UTMZ18")

lines <- readOGR( "boundaryFiles/HARV/",layer = "HARV_roads")

point <- readOGR("boundaryFiles/HARV/", "HARVtower_UTM18N")

I worked my way up to the first On Your Own section. After that, it seemed like everything was still a work in progress. I can test the rest once it is ready!

**Comment by lwasser** [comment]
It's just the cropping part that's a work in progress! But the extract part is good to go!

**Comment by mjones01** [comment]
This section has been updated.  Issue can be closed.
