### ISSUE TITLE
TOO MANY FIELDS in csv files -- clean out the csv files so there are fewer columns

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Spatial-Vector#5]
the plot csv's need to be cleaned up.
We can then potentially add them to figshare so they can be accessed via a URL? . Or we can save them in the lesson repo?

**Comment by mjones01** [comment]
Is this done?  They seemed okay to me going through the lessons.

**Comment by lwasser** [comment]
I need to remove some of the fields. The csv's have 20 fields i think? all we need to do is open them in excel and remove a few. Or open in R and make a new dataframe and export a new CSV. Then reupload to figshare.
