### ISSUE TITLE
Lesson03: Challenge Crop Points

### ISSUE THREAD

**Issue by mjones01** [data-lessons/NEON-R-Spatial-Vector#52]
Challenge currently asks to use the extent of plot locations to crop the raster.  Some of the plot locations are outside the raster so the code isn't working.  Do we want to: 
1) teach removing some points to crop 
or 
2) use a different point shapefile with all points within raster extent?

**Comment by mjones01** [comment]
I believe this is also affecting the code of the last challenge as well.

**Comment by lwasser** [comment]
taught them how to adjust the plot extent using xlims

https://github.com/data-lessons/NEON-R-Spatial-Vector/commit/65c07bb4bd68ea7f2fcf9782940e3e9e67c39921
