### ISSUE TITLE
Image in L00

### ISSUE THREAD

**Issue by mjones01** [data-lessons/NEON-R-Spatial-Vector#54]
Is the plot, line, polygon graphic okay?  I'm concerned that it make it appear that there are curved lines between x,y coordinates instead of the fact that curves are made up of many short, straight lines.

**Comment by lwasser** [comment]
@coolinwilliams can we please revisit the point, line polygon graphic? What i might suggest is that you make the line graphic with the curves a bit more linear with vertices at each "junction" so the shape isn't just a curve.

**Comment by mjones01** [comment]
Updated as of PR#51.   Closing.
