### ISSUE TITLE
Figshare Download

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Spatial-Vector#55]
The zip file is: NEON-DS-Site-Layout-Files-HARV

We should remove "HARV" from the name.
Also, let's talk next week about the name - maybe it should be Site-Infrastructure-Boundary-Files

I am not sure what name is best? Don't worry about implementing this today - let's talk about it in our grey box meeting :) Gosh maybe our grey box meeting should be 2 hours and in vail or someplace we can work - your office??
@mjones01

**Comment by mjones01** [comment]
Currently the zip is NEON-DS-Site-Layout-Files- HARV but the HARV will be dropped as soon as the updated zip are uploaded (check the gDoc Educator Portal - Next Steps - Dec 2015).  

I'm in favor of the shorter name.  Still descriptive, not as long, and other site files could be added to it.

**Comment by lwasser** [comment]
I'm with you on shorter names that leave room for us to add to the data. sounds good.

**Comment by lwasser** [comment]
This has been done.
