### ISSUE TITLE
Images should be credited to NEON rather than NEON, Inc.

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Spatial-Vector#56]
@mjones01  given changes, let's use

National Ecological Observatory Network (NEON) 

throughout!

**Comment by mjones01** [comment]
This pertains to the image source info as well as website links, etc correct?  I'll add it to the list of changes for the grey box meeting as we'll be doing lots of other find and replace.

**Comment by lwasser** [comment]
Yes. sounds good. Do you have a google doc specific to the grey box?  i was just about to go to the template doc but we might want that too.

**Comment by mjones01** [comment]
I'm keeping a list in the issues for the template repository, could move to the gDoc if you prefer.   https://github.com/NEONInc/NEONDS-Template-Repository/issues/7

**Comment by lwasser** [comment]
Ok Here is a doc. 
I'm going to copy the code there just so we can work on it live and then port it to the git site.

**Comment by mjones01** [comment]
This issue was fixed in PRs #59 and #60.
