### ISSUE TITLE
Point line polygon graphic - L00

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Spatial-Vector#64]
@coolinwilliams we need to make a few changes to the point, line polygon graphic in L00
1. Please move the NEON watermark into the graphic on top of the blue box so there isn't extra white space below - it makes the caption below look far away.
2. Point data - please modify the RIGHT column text:
   Points: individual "x,y" locations.
   ex: center point of plot locations (text you have there now)
3. Line data - please modify RIGHT column
   Lines: composed of many (at least 2) vertices, or points, that
   are connected.
   ex:  (text you have there now)
4. Polygon Data- right column
   Polygons: 3 or more ve rtices that are connected and "closed". 
   ex:  (text you have now)

Get in touch with any questions!

**Comment by mjones01** [comment]
Question as to 4 above.  Why have closed in quotes?  We don't have it that way in the text and, while a bit of jargon, I think closed is a common enough term in this context to not need quotes.  If for emphasis, can we use italics instead?
