### ISSUE TITLE
LESSON 00 Challenge

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Spatial-Vector#66]
It might be nice to have a challenge at the end that takes the NEON plot locations in both point and polygon format. The user can plot them and we can ask them questions about each dataset - and how it's stored differently.

**Comment by jsta** [comment]
I think this would work as long as the [Intro to geospatial data lesson](http://neon-workwithdata.github.io/NEON-R-Spatio-Temporal-Data-and-Management-Intro/R/spatial-data-formats) has been covered. I particularly like the section examining the _Stucture of a Lines Feature_. However, at least for lesson 00, I would avoid getting into the details about nested polygons and polygons holes.

**Comment by lwasser** [comment]
This issue was moved to datacarpentry/R-spatial-raster-vector-lesson#97
