### ISSUE TITLE
Heading Levels

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Spatial-Vector#68]
Hi @mjones01 -- i'm noticing some inconsistency with headings in our lessons.

We only use h1 
    #headingOne

for the title. After that we use h2, 3 and 4 for all content in our lessons
    ##headingTwo

The exception is for our grey box where we are using H1 as a hack at the very top :)
I am not sure if this is here from previous lessons of if this was modified in the vector lessons but i just wanted to call attention to it for all of our lessons so we are on the same page! :)

l.

**Comment by mjones01** [comment]
I'm finding lots of h1 use instances in the Raster lessons.  Will fix in here and time-series and then will add to the Operation Manual.

**Comment by lwasser** [comment]
Sounds great! Thank you.
It's probably just inconsistency throughout. 
Leah

**Comment by lwasser** [comment]
I
