### ISSUE TITLE
Lesson 01 - In the challenge that i wrote - when you attempt to apply unique line widths by attribute it responds oddly

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Spatial-Vector#69]
The Resulting map should have all lines where bikes are allowed in a wider thickness. However instead it makes some wide and some not wide. I am not sure why right now so i remove the line width part. but this is a bug for us to sort out for future.

**Comment by mjones01** [comment]
It is also unclear in the lesson at this point, why some plot in 1 color and the others plot in another color when all that is specified is the line width differences.  line ~287 ###Adjust Line Width header.

**Comment by lwasser** [comment]
Do you mean why some lines are pink and some grey @mjones01 ?

if that is what you are asking, please read the lesson carefully. Just above the challenge i describe how the default color palette is set and how you can modify it to force R to use the colors that you want WITHOUT specifying colors in the plot itself. If you look at the code for the actual answer in the challenge, notice i set the palette `palette(c("magenta","grey","grey"))`. Is this what you are referring to?

```
#set colors so only the allowed roads are magenta
palette(c("magenta","grey","grey"))
palette()
#plot using new colors
plot(lines_HARV, col=lines_HARV$BicyclesHo,
     lwd=4,
     main="Roads Where Bikes and Horses Are Allowed \n NEON Harvard Forest Field Site")
#add a legend to our map
legend("bottomright", 
       levels(lines_HARV$BicyclesHo), 
       fill=palette(), 
       bty="n", cex=.8)

```

If this is not what you are referring to, please let me know if something else is weird in that plot that i'm missing. The line width thing is baffling.

**Comment by mjones01** [comment]
I added by specific comments to the PR #81  as it was easier to explain line by line.

**Comment by lwasser** [comment]
Ok - the line width issue is figured out. SUPER easy simple fix!! R definitely wants to plot by FEATURE by default. Thus you create vector of desired line widths / PCH values etc. fixed!

```
#view the factor levels
levels(lines_HARV$TYPE)
#create vector of line width values
lineWidth <- c(6,4,1,2)[lines_HARV$TYPE]
#view vector
lineWidth
#adjust width of each level
#in this case, boardwalk (the first level) is the widest.
plot(lines_HARV, 
     col=lines_HARV$TYPE,
     main="Roads at the NEON Harvard Forest Field Site \n Boardwalks & Footpath Lines Are Thick",
     lwd=lineWidth)
```
