### ISSUE TITLE
Data - L03 - CSV needs to be edited

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Spatial-Vector#70]
As is the CSV has a lot of addition fields in it. We should remove either the X and Y fields or the easting and northing. Given this is an intro lesson, maybe easting and northing should go. 

We should also remove the following Fields:
- subtypeSpe
- coordinate
- minimumEle (empty)
- maximumEle *empty)
  *inclusionP
- coordinatea_1
- recordedDa
- filteredPo
  *plotPDOP (GPS stuff)
  PlotHDOP
- applicable
- module

We should then have a breakout stating that often x,y will be easting and northing if it's UTM!

I should then create an EML file potentially (maybe a future issue)

**Comment by lwasser** [comment]
This has been done. Still need to upload to figshare so will leave this open until the newest data are uploaded. @mjones01 i just emailed the latest data. When this is uploaded to figshare let's close this issue.

**Comment by mjones01** [comment]
https://ndownloader.figshare.com/files/3672549   New download data link.  New include file uploaded with PR #75
