### ISSUE TITLE
Format spatial data series landing page (also template repo issue)

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Spatial-Vector#73]

**Comment by lwasser** [comment]
@mjones01 please note when you work on the landing page that i started the landing page in this repo for this content. you can use some of that text! When that page is done in the dev server, we can move it here potentially in a template update. let me know if this doesn't make any sense. 
the page won't render properly here because we have a new template layout - but you can steal the text from the .md file.
http://data-lessons.github.io/NEON-R-Spatial-Vector//data-workshop/spatial-vector-series

**Comment by mjones01** [comment]
Landing pages have been updated in Dev server & live pages. Close this issue.

**Comment by lwasser** [comment]
awesome. thanks!
