### ISSUE TITLE
L04: Extract using Buffer. Error in output/text

### ISSUE THREAD

**Issue by mjones01** [data-lessons/NEON-R-Spatial-Vector#74]
L04: http://data-lessons.github.io/NEON-R-Spatial-Vector//R/crop-extract-raster-data-R/

Line 476 Under the Extract Data using x,y Locations header:

"Notice that the command above extracted 1259 pixels from our LiDAR derived canopy
height model. Does this number make sense?"

The output (both on my computer and on the posted page) actually says 1.  One doesn't seem correct as the resolution of the raster is 1x1 (m) so the # of pixels should be closer to 20 x 20.   @lwasser  How did you get 1259?  Any idea why it isn't appearing now?

**Comment by lwasser** [comment]
one is right because the mean function is being run. i'm still editing these lessons so i'm not sure what you are working on.

**Comment by mjones01** [comment]
This line has been removed from the lesson (PR #81). Closing issue.
