### ISSUE TITLE
L03:  fix/specify location of legend in plot 

### ISSUE THREAD

**Issue by mjones01** [data-lessons/NEON-R-Spatial-Vector#78]
In lesson 3 (http://data-lessons.github.io/NEON-R-Spatial-Vector//R/csv-to-shapefile-R/; plot title:Extent Boundary of Plot Locations compared to the AOI Spatial Object  _or_ code: ~ line 328, code chunk `r compare-extents`) a plot of the object boundaries is created with a legend denoting which boundary is which.  However, all of the default legend locations cause the legend symbols or words to overlap with one or more of the plotted boundaries.   

Fix code to specify where the legend is so that it doesn't overlap with the boundaries.

**Comment by mjones01** [comment]
The code solution can also be applied to the first plot in L04.  
http://data-lessons.github.io/NEON-R-Spatial-Vector//R/crop-extract-raster-data-R/; Extent Boundary of Several Spatial Files  -or- ~ line 140;  chunk `r view-extents, echo=FALSE, results='hide'`

**Comment by lwasser** [comment]
Yup - i am having a hard time with this legend issue. i've had it in other lessons. I think the best hack "fix" is to force the extent of the plot to be a bit larger than it needs to be. that way there is space for the legend. so set xlim on the right to a location further east. For the time being however it is fine in terms of the workshops.

**Comment by lwasser** [comment]
Temporary fix - L03 complete: Will keep this open as it is possible to plot the legend outside of the axis using xpcd but we need to figure out best approach.

plot(extent(plot.locationsSp_HARV),
     col="purple", 
     xlab="easting",
     ylab="northing", lwd=8,
     main="Extent Boundary of Plot Locations \nCompared to the AOI Spatial Object",
     ylim=c(4712400,4714000)) #extent the y axis to make room for the legend

**Comment by mjones01** [comment]
Also see Raster L00, code section ```{r classified-elevation-map, echo=FALSE}  for placing legend next to/outside of plot.  This is used for an example plot, not taught in the lesson.

**Comment by lwasser** [comment]
Yup -- we did that in that lesson but it uses PAR and that is really complicated as a concept to teach given everything else. We just used that to render (if its the example i'm thinking of). i fixed throughout by just adjusting the plot extent. it works fine and is simple and easy to explain given we explain extents in these lessons.  closing!
