### ISSUE TITLE
Add `subtype` to HARV_PlotLocations.csv

### ISSUE THREAD

**Issue by mjones01** [data-lessons/NEON-R-Spatial-Vector#79]
Add `subtype` to NEON-DS-Site-Layout-Files/HARV/HARV_PlotLocations.csv

This is parallel to an attribute in NEON-DS-Site-Layout-Files/HARV/HARV_2NewPhenPlots.csv.  Subtype = phenology

What is the subtype for HARV_PlotLocations.csv?   vegetation ?

**Comment by lwasser** [comment]
basePlot

I just emailed you the original full file. But just use basePlot for the others.

**Comment by mjones01** [comment]
Added `subtype`=`basePlot` to NEON-DS-Site-Layout-Files/HARV/HARV_PlotLocations.csv

Change will be included in the next FigShare upload and _include file PR to Template folder (both presumably today).
