### ISSUE TITLE
Shapefile / Vector Data - Include File does not seem to generate the most current data

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Spatial-Vector#82]
@mjones01 is the include file in the vector lessons dated? When i downloaded the data, I do not see the census data layers that we added in the previous round of edits.

**Comment by lwasser** [comment]
Also looking at figshare, there are system files in the zip

https://figshare.com/articles/Spatio_temporal_Series_Teaching_Data_Subsets/2009586

There are different ways to do this but one is at the command line

http://superuser.com/questions/198569/compressing-folders-on-a-mac-without-the-ds-store

But the other might be to use a tool to help with the zipping that ignores system files. Let me know if you need help with this. 
This tool looks like it could be useful:

http://www.sopht.jp/en/cleanarchiver/

**Comment by mjones01** [comment]
The updated files  (not revised since your .DS compressing note above) are in a pending PR in the Template Repo.  My understanding of the workflow was to update to the Template first (there are major text changes, not just the updated download code) and then to copy over to the other individual repos. This ensures that the Template repo is always up to date.  Please correct me if this is not how you want to proceed.  

I'll work on the compressing without .DS files today.

**Comment by lwasser** [comment]
Perfect. This is the desired workflow! I'll wait for you to fix the download, will merge the template repo when this is up to date. Then will update the includes in this repo with my next build. Thank you, Megan. Assigning this to myself.

**Comment by mjones01** [comment]
To remove systems files from already created zip files use (on Macs): 
`zip -d filename.zip __MACOSX/\* \*/.DS_Store`

**Comment by mjones01** [comment]
Added the needed column (Issue #79) to the Site_Layout_Files.zip.  I did NOT change files mentioned in lessons' issues that also required changes to the lesson text/code. Template repo PR now staged for merge.

**Comment by lwasser** [comment]
Awesome! We should document this in the educator portal documentation. Will you please add it? Maybe we should create a "Data subsets" document and document it there along with the information on figshare. This document will be just a few lines to begin with. Thank you, Megan!

**Comment by mjones01** [comment]
Already done.  Check out the section titled "Data Sets on FigShare".  There still needs to be a lot more added but it is a start.  https://docs.google.com/document/d/19aw90rY3LKkGbn-y1ggY4VW1hEi7-l20YStqu30en7k/edit?usp=sharing

**Comment by mjones01** [comment]
I've been adding to the Ed Portal Documentation document about things I've been doing.  Some of these will likely need to be updated as our workflow has (and will continue) to change but at least it is the start of the record.

**Comment by lwasser** [comment]
Wonderful! Thank you!
There is a possibility that we may be asked to provide documentation so it's good to document as we go even if we have to fill in a bit along the way.

**Comment by lwasser** [comment]
Fixed - closing.  d01d5567efa94c0c0bd3636762bc7d4875023456
