### ISSUE TITLE
L01: line width (lwd) not plotting properly

### ISSUE THREAD

**Issue by mjones01** [data-lessons/NEON-R-Spatial-Vector#83]
This issue overlaps with  Issue #69. 

L01 teaches plotting by attributes including plotting different colors and line widths.  However, the line width is not plotting as expected in the lesson or in the challenge (specifically mentioned in Issue #69).  One attribute appears with multiple line widths.

**Comment by lwasser** [comment]
@mjones01 thank you. I have a theory that i'm testing. I think that we are not plotting line width by factor - we are plotting by feature. This makes sense given what we are doing. I'll figure out a solution.
I don't know why this didn't hit me sooner!

Thank you!
Leah

**Comment by mjones01** [comment]
@lwasser  If you have other things to work on I talked to Mike about the problem last night.  He said he's worked a lot with plotting vector's in R and is happy to work on it if we want him to.  Just let me know and I'll tell him to fork and work on it.

**Comment by mjones01** [comment]
@lwasser  If you have other things to work on I talked to Mike about the problem last night.  He said he's worked a lot with plotting vector's in R and is happy to work on it if we want him to.  Just let me know and I'll tell him to fork and work on it.

**Comment by lwasser** [comment]
This has been fixed per the issue comments below! closing.

https://github.com/data-lessons/NEON-R-Spatial-Vector/issues/69
