### ISSUE TITLE
interested in reviewing the repo

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Spatial-Vector#86]
Hi @jsta - I am sorry we have been out of touch! We have done a good bit of work to the vector lessons. Do you have any time / interest in reviewing them in their current state?

We'd love your input, feedback given you originally pulled them all together!! We also understand busy schedules and not having time do work on things given such schedules. Feel free to say "not now" or maybe "just one lesson". whatever works for you!
Leah :)

**Comment by jsta** [comment]
Yes. I will take a look. Seems like quite a lot of effort went in to setting up the rendering and style.

**Comment by lwasser** [comment]
Thank you, @jsta !! Yes, we have been working on the rendering - largely because we needed to update things on the NEONdataskills.org site to support these lessons AND because they just did a big Jekyll update which was causing some things to break :) Looking forward to your feedback when you have time!

**Comment by lwasser** [comment]
@jsta thank you again for the feedback!! it's much appreciated. Edits have been merged, the lessons rebuilt and posted to the repo AND to posted to http://neondataskills.org/tutorial-series/vector-data-series/ - their final build landing place :)
