### ISSUE TITLE
Set working directory lesson

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Spatial-Vector#88]
There is a link to the set working directory background page that needs to be adjusted throughout the lessons once the background lessons is done.

**Comment by mjones01** [comment]
The PR for the set working directory lesson is pending in the Lesson Development repo.  The link should work once the lesson is within the same repo (Data-Skills) as the lessons linking to it.

**Comment by lwasser** [comment]
Wonderful, when it's ready to review again please let me know. I'll merge, push to DS and we can move forward with updating links throughout the lessons as needed! We can always tweak it later if need be :)

**Comment by mjones01** [comment]
This issue can be closed.  The Set Working Directory lessons is in DS-Dev and now live on the site as well!

**Comment by lwasser** [comment]
Woo hoo!!
