### ISSUE TITLE
Remove ggplot from l05 

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Spatial-Vector#89]
as written, it's not currently taught - so it's not needed in the L05 introduction!

**Comment by mjones01** [comment]
I'm working on copying all the R packages into the Series Landing Pages right now.  I'll remove this from Vector 05 as I'll have the file open.

**Comment by lwasser** [comment]
Ok - be sure to pull the latest version of vector down as I Merged Joe's edits this morning.
Thank you!
Leah

**Comment by mjones01** [comment]
Done.  Commit  https://github.com/mjones01/NEON-R-Spatial-Vector/commit/f7c47690ca06ce453f22cd7c698ffe010c7b42d9  .  PR ready for merge.  
Issue can be closed.
