### ISSUE TITLE
V00 Challenge points to V01 for help

### ISSUE THREAD

**Issue by mjones01** [data-lessons/NEON-R-Spatial-Vector#93]
The wrap up  Challenge: Plot Raster & Vector Data Together in Vector 00 refers to Vector 01 if the participants need help.  Referring to a tutorial that hasn't yet been taught seems counter to our lesson progression.  Additionally, I'm not exactly what skills V01 adds to help with that challenge. 

Suggestion: Review this challenge again after the lesson has been tested in a workshop.  If participant do fine then perhaps revise the help text. If they struggle then the challenge might need to move later in the progression.

**Comment by lwasser** [comment]
This issue was moved to datacarpentry/R-spatial-raster-vector-lesson#96
