### ISSUE TITLE
vector lesson 01 - a few issues

### ISSUE THREAD

**Issue by natalie-robinson** [data-lessons/NEON-R-Spatial-Vector#97]
- [ ] Line 186 should say that “# in this case, boardwalk (the first level) is the narrowest.”  (Not widest)
- [x] In the legend for state boundaries (line 308), there is no “region” attribute for the dataset. You can color code based on State.Boundery.US$NAME (and you’ll need to adjust the objects above to have the right numbers of colors), or _make_ regions (seems a big pain)…

**Comment by jsta** [comment]
Hmm, thanks for checking this out. Looking into it now.

**Comment by jsta** [comment]
I am about to commit a fix for item 1. I think the easiest solution for item 2 is to update the shapefile with a `region` field.

**Comment by jsta** [comment]
@lwasser Here is a solution for item 2: 

```
State.Boundary.US <- readOGR("../_data/US-Boundary-Layers", "US-State-Boundaries-Census-2014")

region_key <- read.table(text = "
NJ,Northeast
NH,Northeast
NV,West
KS,Midwest
VT,Northeast
PA,Northeast
ND,Midwest
AL,Southeast
RI,Northeast
DE,Northeast
WY,West
WV,Southeast
WA,West
UT,West
SD,Midwest
SC,Southeast
OK,Southwest
MT,West
MS,Southeast
MA,Northeast
ME,Northeast
OH,Midwest
NC,Southeast
NM,Southwest
NE,Midwest
CT,Northeast
IN,Midwest
CO,West
AR,Southeast
AZ,Southwest
WI,Midwest
VA,Southeast
TX,Southwest
TN,Southeast
OR,West
NY,Northeast
MO,Midwest
MN,Midwest
MI,Midwest
MD,Northeast
LA,Southeast
KY,Southeast
IA,Midwest
IL,Midwest
ID,West
GA,Southeast
FL,Southeast
DC,Southeast
CA,West", sep = ",")
names(region_key) <- c("STUSPS", "region")

State.Boundary.US <- merge(State.Boundary.US, region_key)

levels(State.Boundary.US$region)
colors <- c("purple","springgreen","yellow","brown","grey")
colors

plot(State.Boundary.US,
         col=(colors)[State.Boundary.US$region],
         main="Contiguous U.S. State Boundaries \n 50 Colors")
```

**Comment by lwasser** [comment]
THANK YOU BOTH! What a good catch.
I actually had added a region field to the shapefile. However perhaps figshare never was updated? I have attached this file to this issue to see if the updated file attached to the issue. If it does, will you please see if this layers works for you?

@mjones01 do you happen to know if this update ever happened in figshare OR if the download link is maybe dated?

Thank you
Leah

**Comment by lwasser** [comment]
[new-UsBoundaries-layer.zip](https://github.com/data-lessons/NEON-R-Spatial-Vector/files/213426/new-UsBoundaries-layer.zip) 

trying again to attach the shapefile!

**Comment by mjones01** [comment]
We figured out the issue.  Our _include file with the updated download link didn't get moved from this repo to the live site repo.  The correct file downloads here: http://data-lessons.github.io/NEON-R-Spatial-Vector/R/shapefile-attributes-in-R/ 

Leah or I will make sure this is fixed by this evening.  Thank you for the catch!

**Comment by natalie-robinson** [comment]
The coloring by region is working like a charm with the new file!

**Comment by lwasser** [comment]
Phew! Ok awesome. I'm going to update the download link now. Presumably, we will have issues tomorrow with some people having the older file SO.... We can have them download it in Git. let's start the day with that - if we place it in the ether pad, they can download it that way.

**Comment by mjones01** [comment]
I've added a note to update and added the direct FigShare download link to the Etherpad. http://pad.software-carpentry.org/gqkzFs2w9Q

**Comment by lwasser** [comment]
addressed - closing!
