### ISSUE TITLE
raster lesson 05 - data missing for plot

### ISSUE THREAD

**Issue by natalie-robinson** [data-lessons/NEON-R-Spatial-Vector#98]
When folks download the script for the lesson, there is a section for plotting mean daily air temp at HARV, from a csv. That csv is not part of the data download for the lesson, so users cannot get the data as of now.

**Comment by lwasser** [comment]
Oh -- right. you mean a graphic on the lesson but something we don't teach, right? Another great catch!

I bet that is confusing huh! i never thought about that. you know throughout our lessons we have graphics that i've created using code from data that are not i the actual lesson.

One option it i may be able to hide that chunk so it doesn't write to the .R file when we purl it? Do you think that would be better / less confusing?

@jsta do you have any thoughts on this? essentially sometimes i just use data to create figures to demonstrate a point  - but that data isn't always used in the lesson. You can download the .R script at the bottom of the page however and see all of the code! So one option could be to turn off the chunk so it doesn't get written to the R script. thoughts? 

leah

**Comment by mjones01** [comment]
I think the most efficient fix would be to make a comment note in that code chunk explaining what it is and why.  The participants might not be able to create it, but they can see the code that would allow them to do so if they want to create a similar plot.  

Specifically for this instance, this is data (and plot) from the time series tutorials (http://neondataskills.org/R/Work-With-NDVI-and-Met-Data-In-R/), so we can simply refer them to those lessons if they want the data. 

Thoughts on this solution?

**Comment by lwasser** [comment]
I think that is a great solution. We can link to the download in the chunk as a comment.

**Comment by jsta** [comment]
:+1: to that solution

**Comment by lwasser** [comment]
This issue was moved to datacarpentry/R-spatial-raster-vector-lesson#91
